// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina WSDL tool.

import ballerina/data.xmldata;
import ballerina/http;

public isolated client class Client {
    final http:Client clientEp;

    public isolated function init(string serviceUrl = "https://api-uat.grsportal.com/PartnerApi.php", *http:CorsConfig config) returns error? {
        self.clientEp = check new ("");
    }
}

@xmldata:Namespace {prefix: "soap", uri: "http://schemas.xmlsoap.org/soap/envelope/"}
public type placeOrderHeader record {
    @xmldata:Name {value: "AuthHeaderElement"}
    @xmldata:Namespace {prefix: "AuthHeader", uri: "http://api.grsportal.com/"}
    AuthHeaderElement AuthHeader?;
};

public type placeOrderResponseBody record {
    ApiOrderStatusElement ApiOrderStatusElement?;
};

@xmldata:Name {value: "Envelope"}
public type placeOrderSoapResponse record {
    placeOrderResponseBody Body;
};

@xmldata:Namespace {prefix: "soap", uri: "http://schemas.xmlsoap.org/soap/envelope/"}
public type placeOrderRequestBody record {
    AuthHeaderElement AuthHeaderElement?;
};

@xmldata:Name {value: "Envelope"}
@xmldata:Namespace {prefix: "soap", uri: "http://schemas.xmlsoap.org/soap/envelope/"}
public type placeOrderSoapRequest record {
    @xmldata:Namespace {prefix: "soap", uri: "http://schemas.xmlsoap.org/soap/envelope/"}
    placeOrderHeader Header?;
    @xmldata:Namespace {prefix: "soap", uri: "http://schemas.xmlsoap.org/soap/envelope/"}
    placeOrderRequestBody Body;
};
