// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina WSDL tool.

import ballerina/data.xmldata;

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type AuthHeader record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup sequenceGroup;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type AuthHeaderElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup sequenceGroup;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiGallery record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup1 sequenceGroup1;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiGalleryElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup1 sequenceGroup1;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiGalleryArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup2 sequenceGroup2;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiGalleryArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup2 sequenceGroup2;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalog record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup3 sequenceGroup3;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup3 sequenceGroup3;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type StringArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup4 sequenceGroup4;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type StringArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup4 sequenceGroup4;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogAttribute record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup5 sequenceGroup5;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogAttributeElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup5 sequenceGroup5;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogAttributeArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup6 sequenceGroup6;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogAttributeArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup6 sequenceGroup6;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogOption record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup7 sequenceGroup7;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogOptionElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup7 sequenceGroup7;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogOptionArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup8 sequenceGroup8;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogOptionArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup8 sequenceGroup8;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup9 sequenceGroup9;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCatalogArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup9 sequenceGroup9;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategory record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup10 sequenceGroup10;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup10 sequenceGroup10;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryImage record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup11 sequenceGroup11;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryImageElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup11 sequenceGroup11;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryImageArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup12 sequenceGroup12;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryImageArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup12 sequenceGroup12;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup13 sequenceGroup13;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiCategoryArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup13 sequenceGroup13;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiBrand record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup14 sequenceGroup14;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiBrandElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup14 sequenceGroup14;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiBrandArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup15 sequenceGroup15;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiBrandArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup15 sequenceGroup15;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOption record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup16 sequenceGroup16;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOptionElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup16 sequenceGroup16;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOptionArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup17 sequenceGroup17;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOptionArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup17 sequenceGroup17;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardContainer record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup18 sequenceGroup18;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardContainerElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup18 sequenceGroup18;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiSmallReward record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup19 sequenceGroup19;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiSmallRewardElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup19 sequenceGroup19;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardImage record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup20 sequenceGroup20;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardImageElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup20 sequenceGroup20;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardImageArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup21 sequenceGroup21;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardImageArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup21 sequenceGroup21;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiSmallRewardArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup22 sequenceGroup22;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiSmallRewardArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup22 sequenceGroup22;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiLargeReward record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup23 sequenceGroup23;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiLargeRewardElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup23 sequenceGroup23;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardOption record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup24 sequenceGroup24;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardOptionElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup24 sequenceGroup24;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardOptionArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup25 sequenceGroup25;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiRewardOptionArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup25 sequenceGroup25;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrder record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup26 sequenceGroup26;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup26 sequenceGroup26;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItem record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup27 sequenceGroup27;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup27 sequenceGroup27;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemOption record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup28 sequenceGroup28;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemOptionElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup28 sequenceGroup28;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemOptionArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup29 sequenceGroup29;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemOptionArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup29 sequenceGroup29;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup30 sequenceGroup30;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup30 sequenceGroup30;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderStatus record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup31 sequenceGroup31;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderStatusElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup31 sequenceGroup31;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemStatus record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup32 sequenceGroup32;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemStatusElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup32 sequenceGroup32;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemHistoryEvent record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup33 sequenceGroup33;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemHistoryEventElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup33 sequenceGroup33;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemHistoryEventArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup34 sequenceGroup34;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemHistoryEventArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup34 sequenceGroup34;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemStatusArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup35 sequenceGroup35;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderItemStatusArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup35 sequenceGroup35;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerContainer record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup36 sequenceGroup36;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerContainerElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup36 sequenceGroup36;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimer record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup37 sequenceGroup37;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup37 sequenceGroup37;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup38 sequenceGroup38;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup38 sequenceGroup38;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerResponse record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup39 sequenceGroup39;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPlateauPrimerResponseElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup39 sequenceGroup39;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPartnerAccessResponse record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup40 sequenceGroup40;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiPartnerAccessResponseElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup40 sequenceGroup40;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiMemberDetails record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup41 sequenceGroup41;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiMemberDetailsElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup41 sequenceGroup41;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiMemberAccessResponse record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup42 sequenceGroup42;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiMemberAccessResponseElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup42 sequenceGroup42;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderValidationStatus record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup43 sequenceGroup43;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiOrderValidationStatusElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup43 sequenceGroup43;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type AnyTypeArray record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup44 sequenceGroup44;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type AnyTypeArrayElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup44 sequenceGroup44;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiProductAvalableStatus record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup45 sequenceGroup45;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type ApiProductAvalableStatusElement record {|
    @xmldata:Sequence {minOccurs: 1, maxOccurs: 1}
    SequenceGroup45 sequenceGroup45;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string apiToken;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string galleryId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string language;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string country;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup1 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string status;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup2 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiGallery[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup3 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int rootCategoryId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string code;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    boolean canHoldOrders;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    StringArray countries;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    StringArray languages;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    string 'type;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    string imageUrl;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 10}
    ApiCatalogAttributeArray attributes;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 11}
    ApiCatalogOptionArray options;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup4 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup5 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string value;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string appliesTo;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup6 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiCatalogAttribute[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup7 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string 'type;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    boolean isMandatory;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup8 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiCatalogOption[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup9 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiCatalog[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup10 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int rank;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    boolean hasChildren;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    int rewardCount;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    ApiCategoryImageArray images;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    ApiCategoryArray children;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    int parentId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    string parentName;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup11 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int width;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int height;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string url;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    boolean isDefault;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup12 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiCategoryImage[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup13 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiCategory[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup14 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int rewardCount;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup15 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiBrand[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup16 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string value;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup17 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiOption[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup18 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int page;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int totalPages;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    int rewardsPerPage;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    int rewardsFrom;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    int rewardsTo;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    int totalRewards;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    boolean paginationNeeded;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    ApiSmallRewardArray apiSmallRewards;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup19 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string brand;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    float cost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    float productCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    float shippingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    float handlingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    float serviceCharge;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    float regularTotalCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 10}
    float regularProductCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 11}
    float regularShippingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 12}
    float regularHandlingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 13}
    float regularServiceCharge;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 14}
    boolean isOnSale;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 15}
    ApiRewardImageArray images;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup20 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int size;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string url;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup21 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiRewardImage[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup22 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiSmallReward[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup23 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string brand;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string model;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    string description;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    string termsAndConditions;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    string sku;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    ApiRewardOptionArray options;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    float productCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 10}
    float shippingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 11}
    float handlingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 12}
    float serviceChargeCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 13}
    float cost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 14}
    float regularProductCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 15}
    float regularShippingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 16}
    float regularHandlingCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 17}
    float regularServiceChargeCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 18}
    float regularTotalCost;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 19}
    boolean isOnSale;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 20}
    float msrp;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 21}
    ApiRewardImageArray images;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup24 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string 'type;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    StringArray values;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    boolean isMandatory;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup25 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiRewardOption[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup26 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string businessName;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string firstName;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string lastName;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string refNumber;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    string address1;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    string address2;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    string city;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    string provinceState;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    string country;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 10}
    string postalCode;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 11}
    string phone;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 12}
    string email;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 13}
    string specialInstructions;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 14}
    boolean isBusinessAddress;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 15}
    ApiOrderItemArray orderItems;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup27 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int rewardId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int catalogId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    int quantity;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string partnerOrderNumber;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    ApiOrderItemOptionArray options;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup28 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int id;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string value;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup29 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiOrderItemOption[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup30 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiOrderItem[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup31 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int orderId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string status;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    ApiOrderItemStatusArray orderItemStatuses;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup32 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string lineItemId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string status;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string extra;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string partnerOrderNumber;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    ApiOrderItemHistoryEventArray orderItemHistory;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    StringArray details;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup33 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string name;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string note;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup34 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiOrderItemHistoryEvent[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup35 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiOrderItemStatus[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup36 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiPlateauPrimerArray apiPlateauPrimers;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup37 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    int galleryId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    int catalogId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    int categoryId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string countryCode;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    string languageCode;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    int depth;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    string urlScheme;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    int recordsPerPage;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    string sortField;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 10}
    string sortDirection;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 11}
    string apiOptionName;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 12}
    string apiOptionValue;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 13}
    string context;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 14}
    int min;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 15}
    int max;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 16}
    boolean enabled;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 17}
    string uniqueHash;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup38 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    ApiPlateauPrimer[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup39 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    boolean success;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup40 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    boolean success;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string message;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string imageURL;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup41 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    string memberId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string memberFirstname;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string memberLastname;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 4}
    string language;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 5}
    string country;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 6}
    string memberEmail;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 7}
    string pointName;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 8}
    string pointBalance;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 9}
    int roundTo;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 10}
    string clientId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 11}
    string clientName;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 12}
    float basePointMultiplier;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 13}
    float partnerMarkupMultiplier;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 14}
    float partnerTaxMultiplier;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 15}
    string logoImageURL;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 16}
    string branding;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 17}
    string sessionId;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 18}
    string baseURL;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup42 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    boolean success;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    string message;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 3}
    string memberAccessURL;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup43 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    boolean validStatus;
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 2}
    AnyTypeArray orderItemErrors;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup44 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    anydata[] item?;
|};

@xmldata:Namespace {uri: "http://api.grsportal.com/"}
public type SequenceGroup45 record {|
    @xmldata:Namespace {uri: "http://api.grsportal.com/"}
    @xmldata:SequenceOrder {value: 1}
    boolean productAvailable;
|};
